[project]
name = "struct_codes"
version = "0.1.0"
description = "Package for strucutral code checking"
readme = "README.md"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

